AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  YBWSContactForm:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::148849141066:role/service-role/Bitrix24Lambda'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /
            Method: GET
      Environment:
        Variables:
          domain: bedrosova.bitrix24.ru
          hook: 'https://bedrosova.bitrix24.ru/rest/1/**************/'
          key: ******************
      Layers:
        - 'arn:aws:lambda:us-east-1:148849141066:layer:requests:1'
        - 'arn:aws:lambda:us-east-1:148849141066:layer:bitrix24:1'
