AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  YBWSServerlessWebSite:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::148849141066:role/service-role/Bitrix24Lambda'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /YBWSServerlessWebSite
            Method: GET
        Api2:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
        Api3:
          Type: Api
          Properties:
            Path: /YBWSServerlessWebSite
            Method: GET
        Api4:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
